// Barrel re-export giữ API surface cũ không vỡ.
export {
  getCurrentAdminRole,
  listAdminTablePage,
  requireAdmin,
  type AdminAnalytics,
  type AdminContentReadiness,
  type AdminDraft,
  type AdminEmailDelivery,
  type AdminLearnerDetail,
  type AdminLessonExercise,
  type AdminTablePage,
  type AdminTablePageOptions,
  type AdminReviewOption,
  type AdminStaffMember,
  type AdminStaffRole,
  type AdminWeakTopic,
} from './adminRepositoryCore';

export {
  createAdminCourse,
  deleteAdminCourse,
  deleteAdminDocument,
  deleteAdminLesson,
  deleteAdminLessonAsset,
  deleteAdminLessonExercise,
  deleteAdminModule,
  deleteAdminAudio,
  deleteAdminVocabulary,
  listAdminAudio,
  listAdminCourses,
  listAdminDocuments,
  listAdminLessonAssets,
  listAdminLessonExercises,
  listAdminLessons,
  listAdminLessonVocabulary,
  listAdminModules,
  listAdminVocabulary,
  replaceAdminLessonVocabulary,
  saveAdminAudio,
  saveAdminDocument,
  saveAdminLesson,
  saveAdminLessonAsset,
  saveAdminLessonExercise,
  saveAdminModule,
  saveAdminVocabulary,
  updateAdminCourse,
} from './adminContentRepository';

export {
  deleteAdminAssessment,
  deleteAdminAssessmentQuestion,
  deleteAdminReviewQuestion,
  listAdminAssessmentQuestions,
  listAdminAssessments,
  listAdminContentRevisions,
  listAdminReviewOptions,
  listAdminReviewQuestions,
  publishAdminContent,
  rollbackAdminContentRevision,
  saveAdminAssessment,
  saveAdminAssessmentQuestion,
  saveAdminReviewQuestion,
} from './adminAssessmentRepository';

export {
  deleteAdminGrammarExample,
  deleteAdminGrammarRule,
  deleteAdminGrammarTopic,
  deleteAdminSpeakingPrompt,
  listAdminGrammarExamples,
  listAdminGrammarRules,
  listAdminGrammarTopicCourses,
  listAdminGrammarTopics,
  listAdminSpeakingPrompts,
  replaceAdminGrammarTopicCourses,
  saveAdminGrammarExample,
  saveAdminGrammarRule,
  saveAdminGrammarTopic,
  saveAdminSpeakingPrompt,
} from './adminGrammarRepository';

export {
  deleteAdminPackage,
  deleteAdminPrompt,
  grantAdminEnrollment,
  listAdminEnrollments,
  listAdminPackageCourses,
  listAdminPackages,
  listAdminPrompts,
  replaceAdminPackageCourses,
  revokeAdminEnrollment,
  saveAdminPackage,
  saveAdminPrompt,
} from './adminCommerceRepository';

export {
  fetchAdminLearnerDetail,
  inviteAdminStaff,
  listAdminStaff,
  listAdminStudents,
  removeAdminStaffRole,
  setAdminStaffRole,
  uploadAdminCourseAsset,
} from './adminUsersRepository';

export {
  archiveAdminAnnouncement,
  createAdminAnnouncement,
  createAdminInterventionNote,
  deleteAdminAlert,
  deleteAdminDashboardHeroSlot,
  deleteAdminSitePage,
  fetchAdminAnalytics,
  listAdminActivityLogs,
  listAdminAlerts,
  listAdminAnnouncements,
  listAdminApiKeyMetadata,
  listAdminDashboardHeroSlots,
  listAdminInterventionNotes,
  listAdminSitePages,
  saveAdminAlert,
  saveAdminDashboardHeroSlot,
  saveAdminSitePage,
} from './adminSystemRepository';
