begin;

create index if not exists admin_roles_granted_by_idx on public.admin_roles(granted_by);
create index if not exists ai_conversations_course_id_idx on public.ai_conversations(course_id);
create index if not exists ai_conversations_user_id_idx on public.ai_conversations(user_id);
create index if not exists ai_messages_conversation_id_idx on public.ai_messages(conversation_id);
create index if not exists ai_writing_submissions_course_id_idx on public.ai_writing_submissions(course_id);
create index if not exists ai_writing_submissions_prompt_id_idx on public.ai_writing_submissions(prompt_id);
create index if not exists announcements_course_id_idx on public.announcements(course_id);
create index if not exists announcements_created_by_idx on public.announcements(created_by);
create index if not exists assessment_attempts_assessment_id_idx on public.assessment_attempts(assessment_id);
create index if not exists assessment_attempts_user_id_idx on public.assessment_attempts(user_id);
create index if not exists community_blocks_blocked_id_idx on public.community_blocks(blocked_id);
create index if not exists community_follows_followed_id_idx on public.community_follows(followed_id);
create index if not exists community_groups_created_by_idx on public.community_groups(created_by);
create index if not exists community_reports_reviewed_by_idx on public.community_reports(reviewed_by);
create index if not exists content_revisions_author_id_idx on public.content_revisions(author_id);
create index if not exists document_annotations_document_id_idx on public.document_annotations(document_id);
create index if not exists document_bookmarks_document_id_idx on public.document_bookmarks(document_id);
create index if not exists enrollments_course_id_idx on public.enrollments(course_id);
create index if not exists grammar_examples_topic_id_idx on public.grammar_examples(topic_id);
create index if not exists grammar_rules_topic_id_idx on public.grammar_rules(topic_id);
create index if not exists grammar_topic_courses_course_id_idx on public.grammar_topic_courses(course_id);
create index if not exists grammar_topic_vocabulary_vocabulary_item_id_idx on public.grammar_topic_vocabulary(vocabulary_item_id);
create index if not exists journal_entries_user_id_idx on public.journal_entries(user_id);
create index if not exists journal_entries_writing_submission_id_idx on public.journal_entries(writing_submission_id);
create index if not exists learner_achievements_achievement_id_idx on public.learner_achievements(achievement_id);
create index if not exists learner_certificates_course_id_idx on public.learner_certificates(course_id);
create index if not exists learner_intervention_notes_learner_id_idx on public.learner_intervention_notes(learner_id);
create index if not exists learner_intervention_notes_staff_id_idx on public.learner_intervention_notes(staff_id);
create index if not exists learning_activity_events_course_id_idx on public.learning_activity_events(course_id);
create index if not exists lesson_progress_lesson_id_idx on public.lesson_progress(lesson_id);
create index if not exists notifications_announcement_id_idx on public.notifications(announcement_id);
create index if not exists notifications_user_id_idx on public.notifications(user_id);
create index if not exists package_courses_course_id_idx on public.package_courses(course_id);
create index if not exists podcast_episodes_lesson_id_idx on public.podcast_episodes(lesson_id);
create index if not exists review_attempts_question_id_idx on public.review_attempts(question_id);
create index if not exists review_attempts_user_id_idx on public.review_attempts(user_id);
create index if not exists site_pages_updated_by_idx on public.site_pages(updated_by);
create index if not exists speaking_prompts_course_id_idx on public.speaking_prompts(course_id);
create index if not exists speaking_submissions_course_id_idx on public.speaking_submissions(course_id);
create index if not exists speaking_submissions_prompt_id_idx on public.speaking_submissions(prompt_id);
create index if not exists speaking_submissions_user_id_idx on public.speaking_submissions(user_id);
create index if not exists vocabulary_progress_vocabulary_item_id_idx on public.vocabulary_progress(vocabulary_item_id);

commit;
